services:
  api-service:
    container_name: badminton-shop-api
    image: badminton-shop-api
    build:
      context: .
      dockerfile: BadmintonShopAPI/Dockerfile
    ports: 
        - "5000:8080"
    volumes:
      - api-service:/app
  sql-server:
    container_name: badminton-shop-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    volumes:
      - sqlserver:/var/opt/mssql
    environment:
      SA_PASSWORD: Password12345@
      ACCEPT_EULA: Y
    
volumes: 
  api-service: 
  sqlserver:

networks:
  api-service:
    driver: bridge
    
